import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./components/Providers";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const sitka = localFont({
  src: [
    {
      path: "../public/fonts/sitka.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sitka",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sitka.variable} h-screen w-screen`}>
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" />
      </head>
      <body
        className={`antialiased h-screen w-screen`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
